[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "zabbix-automation"
version = "0.1.0"
dependencies = [
  "zabbix-utils",
  "pyyaml",
]

[project.scripts]
zabbix-cli = "cli.main:main"
